### ISSUE TITLE
Server Layout Spec

### ISSUE THREAD

**Issue by sr229** [Sayo-nika/server#1]
Server layout spec for API v1 aims to have a more microservice focused application, and to allow us to debug critical points easier for only that part of the service.

We would split Server into two main parts:

 - API Gateway
 - REST Gateway
## API Gateway

The API Gateway uses the [Circuit Breaker](http://www.sczyh30.com/vertx-blueprint-microservice/api-gateway.html) Concept for design strictly due to the fact we have a large amount of people to serve. Read the linked article on how Circuit Breaker does but in a nutshell:
   - It closes a part of a service within a failing count treshold within a period of time
   - It allows fault-tolerancy to prevent large outages.

Essentially, the Gateway is the frontend's singular entry point call and has to be fault-tolerant all the way.

## REST

The REST is the main brain of the application, all endpoints are circuit-breaker-ed from Gateway. This runs on a HA mode to cope up with demand, and Gateway is expected to do the same.

**Comment by sr229** [comment]
In a more simpler concept 

![image](https://user-images.githubusercontent.com/14976516/41652795-ba64ce3e-74b6-11e8-90b3-31f7da6a162b.png)

**Comment by martmists** [comment]
Rest currently handles all gateway stuff (429, 401, 403, etc)
