### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by Ovyerus** [Sayo-nika/server#12]
Add connections to other services (Discord, Github, Gitlab, some others maybe). Show them on profiles. Allow registering (and thus linking) with a connection, or logging in with a connection if user has it connected.

**Comment by sr229** [comment]
We already have the `Connections[]` Property where A connection is a Object that contains the field `name` and the Connection Type - `discord`, `gitlab`, etc.

**Comment by Ovyerus** [comment]
Doesnt look like it got ported to the Python rewrite.

**Comment by sr229** [comment]
Implemented in https://github.com/Sayo-nika/server/commit/5b28302b38ef018d0ae919bcdb33fe42fe8a4bc1
