### ISSUE TITLE
User roles/flags

### ISSUE THREAD

**Issue by Ovyerus** [Sayo-nika/server#15]
There should a thing for users having roles (and a dev only thing for assigning roles), either done through individual flag properties, or a single "permissions" flag which is a bitmask with each bit designating a different role.

__Current roles__
Supporter - donated to Sayonika, apparently only implement post v1.
Sayonika Developer - could be either aesthetics or give access to dev-only features (TBA)
Moderator - has access to the admin queue (unverified mods + dealing with reports)
Editor - cosmetic role showing that the user has access to our Medium publication..

**Comment by Ovyerus** [comment]
Looks like all of these are actually defined except "editor".

**Comment by sr229** [comment]
We have this under Models already, some aren't exactly implemented yet.
