### ISSUE TITLE
Migrate to IPFS

### ISSUE THREAD

**Issue by sr229** [Sayo-nika/server#42]
Currently we use a invite-only pomf service to run Sayonika, but this reduces the likelihood to run it beyond our own configuration. Since we won't be doing much of the hosting, we'll migrate our stuff to IPFS, backporting that feature from Project Aya.

@martmists is assigned to convert the entirety of the owo code to IPFS ones.

**Comment by martmists** [comment]
Got any docs on IPFS?

**Comment by sr229** [comment]
there's a IPFS wrapper for [Python](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjZ--adj9jmAhVDPHAKHavtDk4QFjAAegQIBhAB&url=https%3A%2F%2Fgithub.com%2Fipfs%2Fpy-ipfs-http-client&usg=AOvVaw0E7YUbSdzTBMcmqGNRBzzp) already @martmists.

**Comment by sr229** [comment]
Fulfilled by @Ovyerus on the recent commits.
